import './globals.css'
import localFont from "next/font/local"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Gilroy = localFont({
  src: [
    {
      path: '../../public/fonts/regular.woff2',
      weight: '400'
    },
     {
      path: '../../public/fonts/medium.woff2',
      weight: '500'
    },
    {
      path: "../../public/fonts/semibold.woff2",
      weight: '600'
    },
    
  ],
  variable: '--font-gilroy'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${Gilroy.variable} font-sans`}>{children}</body>
    </html>
  )
}
